name: Dawson Allen
twitter: https://twitter.com/ddawsonnn?lang=en
phone: (765)-722-0935
email: allends@rose-hulman.edu
instagram: https://www.instagram.com/ddawsonn/
slogan: Engineer  Athlete   Visionary
