name: Dawson Allen
twitter: https://twitter.com/ddawsonnn?lang=en
phone: (765)-722-0935
email: allends@rose-hulman.edu
instagram: https://www.instagram.com/ddawsonn/
slogan: Engineer  Athlete   Visionary
address: 5500​ ​Wabash​ ​Avenue, Box​ ​807<br />Terre​ ​Haute,​ ​IN​ ​47803
age: 19
